name: Deploy .NET App

on:
  push:
    branches:
      - main  # or whichever branch you're deploying

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to DigitalOcean via SSH
        env:
          HOST: 159.89.245.206
          USERNAME: root
          TARGET_DIR: /var/www/DotNet-ToDo-App

          PM2_NAME: DotNet-ToDo-App
          DLL_NAME: TaskManager.dll

        run: |
          ssh -o StrictHostKeyChecking=no $USERNAME@$HOST << 'EOF'
            set -e
            echo "Navigating to project folder..."
            cd $TARGET_DIR

            echo "Fetching latest code..."
            git fetch origin
            git reset --hard origin/main

            echo "Publishing .NET app..."
            dotnet publish -c Release -o out

            echo "Restarting PM2 process..."
            if pm2 list | grep -q $PM2_NAME; then
              echo "Restarting existing PM2 app..."
              pm2 restart $PM2_NAME
            else
              echo "Starting new PM2 app..."
              pm2 start "dotnet out/$DLL_NAME" --name $PM2_NAME
            fi

            echo "Saving PM2 state..."
            pm2 save
          EOF





