name: Deploy .NET App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to DigitalOcean
        env:
          HOST: 159.89.245.206
          USERNAME: root
          TARGET_DIR: /var/www/DotNet-ToDo-App
          DLL_NAME: TaskManager.dll
          PM2_NAME: DotNet-ToDo-App

        run: |
          ssh -o StrictHostKeyChecking=no $USERNAME@$HOST << 'EOF'
            set -e
            echo "Navigating to project folder..."
            cd $TARGET_DIR

            echo "Fetching latest code..."
            git fetch origin
            git reset --hard origin/main

            echo "Publishing .NET project from TaskManager/TaskManager.csproj..."
            dotnet publish TaskManager/TaskManager.csproj -c Release -o TaskManager/out

            echo "Restarting or starting PM2..."
            if pm2 list | grep -q "$PM2_NAME"; then
              pm2 restart "$PM2_NAME"
            else
              pm2 start "dotnet TaskManager/out/$DLL_NAME" --name "$PM2_NAME"
            fi

            echo "Saving PM2 process list..."
            pm2 save
          EOF
