name: Deploy .NET App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to DigitalOcean
        run: |
          ssh -o StrictHostKeyChecking=no root@159.89.245.206 << 'EOF'
            set -e
            echo "Navigating to project folder..."
            cd /var/www/DotNet-ToDo-App

            echo "Fetching latest code..."
            git fetch origin
            git reset --hard origin/main

            echo "Publishing .NET project..."
            dotnet publish TaskManager/TaskManager.csproj -c Release -o TaskManager/out

            echo "Restarting or starting PM2..."
            if pm2 list | grep -q "DotNet-ToDo-App"; then
              pm2 restart DotNet-ToDo-App
            else
              pm2 start "dotnet TaskManager/out/TaskManager.dll" --name DotNet-ToDo-App
            fi

            echo "Saving PM2 process list..."
            pm2 save
          EOF



          
